#### Graph AI to Count the Number of Nodes
Note that this is not really a graph AI, as it does not learn a graph by reading nodes and surrounding neighbours.
Structure of this notebook is a reference to https://github.com/the-deep-learners/deep-learning-illustrated

In [1]:
import json
import numpy as np

In [44]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout 
from keras.layers import BatchNormalization 

In [3]:
data_path = '../data/cycle_data.json'

In [4]:
input_file = open(data_path)
graph_data = json.load(input_file)
input_file.close()

In [5]:
x_train = np.asarray(graph_data['x_train'])
y_train = np.asarray(graph_data['y_train'])
x_valid = np.asarray(graph_data['x_valid'])
y_valid = np.asarray(graph_data['y_valid'])

In [6]:
(x_train.shape, y_train.shape)

((10000, 64, 64), (10000,))

In [8]:
x_train = x_train.reshape(10000, 4096).astype('float32')
x_valid = x_valid.reshape(2000, 4096).astype('float32')

In [45]:
n_classes = 2
y_train = keras.utils.to_categorical(y_train, n_classes)
y_valid = keras.utils.to_categorical(y_valid, n_classes)

In [46]:
(x_train.shape, y_train.shape)

((10000, 4096), (10000, 2))

In [47]:
x_train[5000]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [48]:
y_train[5000]

array([1., 0.], dtype=float32)

In [53]:
model = Sequential()

model.add(Dense(128, input_dim=4096, activation='relu'))
model.add(BatchNormalization())


model.add(Dense(2, activation='softmax'))

In [54]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (None, 128)               524416    
                                                                 
 batch_normalization_9 (Batc  (None, 128)              512       
 hNormalization)                                                 
                                                                 
 dense_15 (Dense)            (None, 2)                 258       
                                                                 
Total params: 525,186
Trainable params: 524,930
Non-trainable params: 256
_________________________________________________________________


In [55]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [56]:
model.fit(x_train, y_train,
          batch_size=128, epochs=30, verbose=1,
          validation_data=(x_valid, y_valid))

Epoch 1/30
79/79 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7767 - val_loss: 0.2729 - val_accuracy: 0.9280
Epoch 2/30
79/79 [==============================] - 0s 3ms/step - loss: 0.1100 - accuracy: 0.9908 - val_loss: 0.2156 - val_accuracy: 0.9290
Epoch 3/30
79/79 [==============================] - 0s 3ms/step - loss: 0.0300 - accuracy: 0.9997 - val_loss: 0.1916 - val_accuracy: 0.9290
Epoch 4/30
79/79 [==============================] - 0s 3ms/step - loss: 0.0121 - accuracy: 1.0000 - val_loss: 0.1676 - val_accuracy: 0.9290
Epoch 5/30
79/79 [==============================] - 0s 3ms/step - loss: 0.0067 - accuracy: 1.0000 - val_loss: 0.1223 - val_accuracy: 0.9290
Epoch 6/30
79/79 [==============================] - 0s 3ms/step - loss: 0.0043 - accuracy: 1.0000 - val_loss: 0.0654 - val_accuracy: 0.9290
Epoch 7/30
79/79 [==============================] - 0s 3ms/step - loss: 0.0030 - accuracy: 1.0000 - val_loss: 0.0308 - val_accuracy: 0.9960
Epoch 8/30
79/79 [==

In [62]:
y_valid[0:100]

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [63]:
model.predict(np.reshape(x_valid[0:100], [100, 4096]))

4/4 [==============================] - 0s 1000us/step


array([[6.23018350e-05, 9.99937654e-01],
       [5.07724462e-06, 9.99994874e-01],
       [7.66480589e-05, 9.99923348e-01],
       [1.62056152e-04, 9.99837875e-01],
       [1.85078345e-04, 9.99814928e-01],
       [1.98970374e-04, 9.99801099e-01],
       [1.22697670e-02, 9.87730205e-01],
       [2.51351623e-04, 9.99748647e-01],
       [2.29010286e-04, 9.99770939e-01],
       [1.14707174e-04, 9.99885321e-01],
       [1.23834252e-04, 9.99876142e-01],
       [7.00914427e-07, 9.99999285e-01],
       [8.18088767e-04, 9.99181926e-01],
       [5.66741764e-05, 9.99943376e-01],
       [9.20678722e-05, 9.99907970e-01],
       [1.52257460e-04, 9.99847770e-01],
       [4.01857324e-06, 9.99995947e-01],
       [1.83375319e-04, 9.99816597e-01],
       [1.40322954e-04, 9.99859691e-01],
       [9.99968529e-01, 3.14418539e-05],
       [6.94969858e-05, 9.99930501e-01],
       [5.80783126e-05, 9.99941945e-01],
       [1.07045867e-04, 9.99892950e-01],
       [8.21711728e-05, 9.99917865e-01],
       [6.306420